#!/usr/bin/env bash
set -euo pipefail

# EmberLite 精简版：将 build/.config 映射为 build/config.cmake（OPENEMBER_* CMake 缓存变量）。

BUILD_DIR="${1:-build}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

CONFIG_FILE="${BUILD_DIR}/.config"
if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "Missing ${CONFIG_FILE}. Run menuconfig first." >&2
  exit 1
fi

tp_mode="$(awk '
  BEGIN { m="FETCH" }
  /^CONFIG_OPENEMBER_TP_MODE_VENDOR=y/ { m="VENDOR" }
  /^CONFIG_OPENEMBER_TP_MODE_SYSTEM=y/ { m="SYSTEM" }
  END { print m }
' "${CONFIG_FILE}")"

onoff() {
  local sym="$1"
  if grep -q "^${sym}=y" "${CONFIG_FILE}"; then
    echo ON
  else
    echo OFF
  fi
}

# 旧 .config 无 HAL 开关时保持与迁移前一致（默认启用 HAL）
if ! grep -q "CONFIG_OPENEMBER_ENABLE_HAL" "${CONFIG_FILE}"; then
  hal_enabled=ON
else
  hal_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_HAL)"
fi

hal_alsa="$(awk '
  BEGIN { v="AUTO" }
  /^CONFIG_OPENEMBER_HAL_ALSA_ON=y/ { v="ON" }
  /^CONFIG_OPENEMBER_HAL_ALSA_OFF=y/ { v="OFF" }
  END { print v }
' "${CONFIG_FILE}")"

hal_libusb="$(awk '
  BEGIN { v="AUTO" }
  /^CONFIG_OPENEMBER_HAL_LIBUSB_ON=y/ { v="ON" }
  /^CONFIG_OPENEMBER_HAL_LIBUSB_OFF=y/ { v="OFF" }
  END { print v }
' "${CONFIG_FILE}")"

examples_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_EXAMPLES)"
crypto_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_CRYPTO)"

OUT="${BUILD_DIR}/config.cmake"
mkdir -p "$(dirname "${OUT}")"

{
  echo "# Generated by ${ROOT_DIR}/scripts/kconfig/genconfig.sh — do not edit by hand."
  echo "set(OPENEMBER_THIRD_PARTY_MODE \"${tp_mode}\" CACHE STRING \"Third-party source mode\" FORCE)"
  echo "set_property(CACHE OPENEMBER_THIRD_PARTY_MODE PROPERTY STRINGS FETCH VENDOR SYSTEM)"
  if [[ "${hal_enabled}" == ON ]]; then
    echo "set(OPENEMBER_ENABLE_HAL ON CACHE BOOL \"Build platform HAL (emberlite_hal)\" FORCE)"
    echo "set(OPENEMBER_HAL_ALSA \"${hal_alsa}\" CACHE STRING \"HAL ALSA: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_ALSA PROPERTY STRINGS AUTO ON OFF)"
    echo "set(OPENEMBER_HAL_LIBUSB \"${hal_libusb}\" CACHE STRING \"HAL libusb: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_LIBUSB PROPERTY STRINGS AUTO ON OFF)"
  else
    echo "set(OPENEMBER_ENABLE_HAL OFF CACHE BOOL \"Build platform HAL (emberlite_hal)\" FORCE)"
    echo "set(OPENEMBER_HAL_ALSA \"AUTO\" CACHE STRING \"HAL ALSA: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_ALSA PROPERTY STRINGS AUTO ON OFF)"
    echo "set(OPENEMBER_HAL_LIBUSB \"AUTO\" CACHE STRING \"HAL libusb: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_LIBUSB PROPERTY STRINGS AUTO ON OFF)"
  fi
  if [[ "${examples_enabled}" == ON ]]; then
    echo "set(OPENEMBER_ENABLE_EXAMPLES ON CACHE BOOL \"Build apps/examples\" FORCE)"
  else
    echo "set(OPENEMBER_ENABLE_EXAMPLES OFF CACHE BOOL \"Build apps/examples\" FORCE)"
  fi
  if [[ "${crypto_enabled}" == ON ]]; then
    echo "set(OPENEMBER_ENABLE_CRYPTO ON CACHE BOOL \"Build components/crypto\" FORCE)"
  else
    echo "set(OPENEMBER_ENABLE_CRYPTO OFF CACHE BOOL \"Build components/crypto\" FORCE)"
  fi
} > "${OUT}"

echo "Wrote ${OUT}" >&2
