#!/usr/bin/env bash
set -euo pipefail

# EmberLite 精简版：将 build/.config 映射为 build/config.cmake（OPENEMBER_* CMake 缓存变量）。

BUILD_DIR="${1:-build}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

CONFIG_FILE="${BUILD_DIR}/.config"
if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "Missing ${CONFIG_FILE}. Run menuconfig first." >&2
  exit 1
fi

tp_mode="$(awk '
  BEGIN { m="FETCH" }
  /^CONFIG_OPENEMBER_TP_MODE_VENDOR=y/ { m="VENDOR" }
  /^CONFIG_OPENEMBER_TP_MODE_SYSTEM=y/ { m="SYSTEM" }
  END { print m }
' "${CONFIG_FILE}")"

onoff() {
  local sym="$1"
  if grep -q "^${sym}=y" "${CONFIG_FILE}"; then
    echo ON
  else
    echo OFF
  fi
}

# 旧 .config 无 HAL 开关时保持与迁移前一致（默认启用 HAL）
if ! grep -q "CONFIG_OPENEMBER_ENABLE_HAL" "${CONFIG_FILE}"; then
  hal_enabled=ON
else
  hal_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_HAL)"
fi

hal_alsa="$(awk '
  BEGIN { v="AUTO" }
  /^CONFIG_OPENEMBER_HAL_ALSA_ON=y/ { v="ON" }
  /^CONFIG_OPENEMBER_HAL_ALSA_OFF=y/ { v="OFF" }
  END { print v }
' "${CONFIG_FILE}")"

hal_libusb="$(awk '
  BEGIN { v="AUTO" }
  /^CONFIG_OPENEMBER_HAL_LIBUSB_ON=y/ { v="ON" }
  /^CONFIG_OPENEMBER_HAL_LIBUSB_OFF=y/ { v="OFF" }
  END { print v }
' "${CONFIG_FILE}")"

examples_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_EXAMPLES)"
crypto_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_CRYPTO)"

if ! grep -q "CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_NNG" "${CONFIG_FILE}"; then
  bundle_nng=ON
else
  bundle_nng="$(onoff CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_NNG)"
fi
if ! grep -q "CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_LCM" "${CONFIG_FILE}"; then
  bundle_lcm=ON
else
  bundle_lcm="$(onoff CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_LCM)"
fi
if ! grep -q "CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_ZENOHPICO" "${CONFIG_FILE}"; then
  bundle_zenohpico=ON
else
  bundle_zenohpico="$(onoff CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_ZENOHPICO)"
fi
if ! grep -q "CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_YYJSON" "${CONFIG_FILE}"; then
  bundle_yyjson=ON
else
  bundle_yyjson="$(onoff CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_YYJSON)"
fi
if ! grep -q "CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_LIBYAML" "${CONFIG_FILE}"; then
  bundle_libyaml=ON
else
  bundle_libyaml="$(onoff CONFIG_OPENEMBER_THIRD_PARTY_BUNDLE_LIBYAML)"
fi

enable_nng="$(onoff CONFIG_OPENEMBER_ENABLE_NNG)"
enable_lcm="$(onoff CONFIG_OPENEMBER_ENABLE_LCM)"
enable_zenohpico="$(onoff CONFIG_OPENEMBER_ENABLE_ZENOHPICO)"
enable_yyjson="$(onoff CONFIG_OPENEMBER_ENABLE_YYJSON)"
enable_libyaml="$(onoff CONFIG_OPENEMBER_ENABLE_LIBYAML)"

OUT="${BUILD_DIR}/config.cmake"
mkdir -p "$(dirname "${OUT}")"

{
  echo "# Generated by ${ROOT_DIR}/scripts/kconfig/genconfig.sh — do not edit by hand."
  echo "set(OPENEMBER_THIRD_PARTY_MODE \"${tp_mode}\" CACHE STRING \"Third-party source mode\" FORCE)"
  echo "set_property(CACHE OPENEMBER_THIRD_PARTY_MODE PROPERTY STRINGS FETCH VENDOR SYSTEM)"
  echo "set(OPENEMBER_THIRD_PARTY_BUNDLE_NNG ${bundle_nng} CACHE BOOL \"Bundle: nng\" FORCE)"
  echo "set(OPENEMBER_THIRD_PARTY_BUNDLE_LCM ${bundle_lcm} CACHE BOOL \"Bundle: lcm\" FORCE)"
  echo "set(OPENEMBER_THIRD_PARTY_BUNDLE_ZENOHPICO ${bundle_zenohpico} CACHE BOOL \"Bundle: zenoh-pico\" FORCE)"
  echo "set(OPENEMBER_THIRD_PARTY_BUNDLE_YYJSON ${bundle_yyjson} CACHE BOOL \"Bundle: yyjson\" FORCE)"
  echo "set(OPENEMBER_THIRD_PARTY_BUNDLE_LIBYAML ${bundle_libyaml} CACHE BOOL \"Bundle: libyaml\" FORCE)"
  echo "set(OPENEMBER_ENABLE_NNG ${enable_nng} CACHE BOOL \"Build and link nng\" FORCE)"
  echo "set(OPENEMBER_ENABLE_LCM ${enable_lcm} CACHE BOOL \"Build and link lcm\" FORCE)"
  echo "set(OPENEMBER_ENABLE_ZENOHPICO ${enable_zenohpico} CACHE BOOL \"Build and link zenoh-pico\" FORCE)"
  echo "set(OPENEMBER_ENABLE_YYJSON ${enable_yyjson} CACHE BOOL \"Build and link yyjson\" FORCE)"
  echo "set(OPENEMBER_ENABLE_LIBYAML ${enable_libyaml} CACHE BOOL \"Build and link libyaml\" FORCE)"
  if [[ "${hal_enabled}" == ON ]]; then
    echo "set(OPENEMBER_ENABLE_HAL ON CACHE BOOL \"Build platform HAL (emberlite_hal)\" FORCE)"
    echo "set(OPENEMBER_HAL_ALSA \"${hal_alsa}\" CACHE STRING \"HAL ALSA: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_ALSA PROPERTY STRINGS AUTO ON OFF)"
    echo "set(OPENEMBER_HAL_LIBUSB \"${hal_libusb}\" CACHE STRING \"HAL libusb: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_LIBUSB PROPERTY STRINGS AUTO ON OFF)"
  else
    echo "set(OPENEMBER_ENABLE_HAL OFF CACHE BOOL \"Build platform HAL (emberlite_hal)\" FORCE)"
    echo "set(OPENEMBER_HAL_ALSA \"AUTO\" CACHE STRING \"HAL ALSA: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_ALSA PROPERTY STRINGS AUTO ON OFF)"
    echo "set(OPENEMBER_HAL_LIBUSB \"AUTO\" CACHE STRING \"HAL libusb: AUTO|ON|OFF\" FORCE)"
    echo "set_property(CACHE OPENEMBER_HAL_LIBUSB PROPERTY STRINGS AUTO ON OFF)"
  fi
  if [[ "${examples_enabled}" == ON ]]; then
    echo "set(OPENEMBER_ENABLE_EXAMPLES ON CACHE BOOL \"Build apps/examples\" FORCE)"
  else
    echo "set(OPENEMBER_ENABLE_EXAMPLES OFF CACHE BOOL \"Build apps/examples\" FORCE)"
  fi
  if [[ "${crypto_enabled}" == ON ]]; then
    echo "set(OPENEMBER_ENABLE_CRYPTO ON CACHE BOOL \"Build components/crypto\" FORCE)"
  else
    echo "set(OPENEMBER_ENABLE_CRYPTO OFF CACHE BOOL \"Build components/crypto\" FORCE)"
  fi
} > "${OUT}"

echo "Wrote ${OUT}" >&2
